### ISSUE TITLE
星熊模组防御力计算错误

### ISSUE THREAD

**Issue by zongzi-github** [xulai1001/akdata#12]
护身符模组中有对自身额外的防御力加成，计算器里没有
希望加上1、2星干员dps计算，一些防御力生命的buff计算

**Comment by xulai1001** [comment]
确实没有计算这部分。稍后会进行修正
低星干员的dps没有计算是因为她们“没有技能”，现在的计算器是需要技能这个参数才能运行的。。。
确实应该加一个判断，让没有技能时只计算普攻dps，而且不可计算专精收益

**Comment by xulai1001** [comment]
d288767 修正了该问题。
