### ISSUE TITLE
伊内斯三技能”独影归途“Nan导致伤害为0

### ISSUE THREAD

**Issue by Granine** [xulai1001/akdata#15]
## Reproduce:
- 选择伊内斯三技能”独影归途“

## Issue:
![image](https://user-images.githubusercontent.com/89324736/236608635-bff84354-f045-4a85-b993-82a39b4e874e.png)
![image](https://user-images.githubusercontent.com/89324736/236608657-77f6a82e-3627-441e-bb9f-9b3420c88991.png)
![image](https://user-images.githubusercontent.com/89324736/236608714-0550590b-799b-4375-858d-8a4bbf91d39d.png)

**Comment by xulai1001** [comment]
偷取攻击力计算有误。推测是缪缪的修改动刀了

**Comment by xulai1001** [comment]
https://github.com/xulai1001/akdata/commit/5744b85ff5cdcf74ccfcbb58dbd0561380ea3da5#diff-4ea4d49b94585032b67f718df467d199bedf2e7f804e1e1812ac7ad8000b214dL2183
