### ISSUE TITLE
夜莺二技能计算为法术伤害

### ISSUE THREAD

**Issue by Granine** [xulai1001/akdata#16]
Reproduce：
- 夜莺二技能·
## Issue：
- 技能显示为法伤
## Expected：
- 技能显示为治疗（Heal + 护盾）
![image](https://user-images.githubusercontent.com/89324736/236609503-89282497-e6b8-44d8-9f48-e27225fefb8d.png)

**Comment by xulai1001** [comment]
早期干员的伤害类型是靠说明文字推断的。夜莺2里写了“法术伤害”所以……
解决：dps_specialtags里添加了攻击类型强制标签
