### ISSUE TITLE
右侧干员“复制到右侧”无效

### ISSUE THREAD

**Issue by Granine** [xulai1001/akdata#17]
## Issue：
右侧干员“复制到右侧”无效按钮
## Suggested fix：
- 改成“复制到左侧”
- 或者移除

**Comment by xulai1001** [comment]
这些问题确实改（掩盖）起来都不难，主要是一开始做页面的时候，只考虑了（使用者按照预期顺序去使用）的逻辑，其他逻辑就开摆了。

解决：解决了出现问题的按钮（
https://github.com/xulai1001/akdata/commit/5744b85ff5cdcf74ccfcbb58dbd0561380ea3da5#diff-1576e45ee6057168d83e23c1e549b2725896d2127fc0204044bed1222cb5e50eL171
