### ISSUE TITLE
右侧干员“同分支干员”实际显示分支为左侧干员

### ISSUE THREAD

**Issue by Granine** [xulai1001/akdata#18]
## Issue：
右侧干员“同分支干员”实际分支显示为左侧干员的分支
## Suggested fix：
- 显示右侧干员分支
- 如果是feature建议更改简介为“同分支干员（左侧）”等
## Image：
![image](https://user-images.githubusercontent.com/89324736/236609812-2cb81bf4-b438-4110-80c3-2d41cbb33abc.png)

**Comment by xulai1001** [comment]
确实是Feature。同分支干员只会以第一列的干员为参考
需要增加说明

**Comment by xulai1001** [comment]
暂时把菜单标题改成了“（第一列干员名字）-相同分支的干员”。我再试试直接按照各列来改吧
