### ISSUE TITLE
独自选择右侧干员时数据不显示 （undefined “dps”）

### ISSUE THREAD

**Issue by Granine** [xulai1001/akdata#19]
## Reproduce：
1. 加载页面
2. 选择右侧干员
3. 左侧不变（预备干员头像）
## Issue:
- 干员数据无法计算
- 干员数据不显示
- undefined “dps”
## Image
![image](https://user-images.githubusercontent.com/89324736/236610274-9f5576f8-228e-4ca4-be0c-ab38ccc00064.png)
![image](https://user-images.githubusercontent.com/89324736/236610289-edb877d2-e8b0-4d5d-bfa7-331f01fc97cb.png)

**Comment by xulai1001** [comment]
本来没打算修的。还是需要考虑合理的修改方式。比如只选择第二列时强行摆到第一列？

**Comment by Granine** [comment]
1. 其实如果不麻烦（看html还好？）最好的选项可以直接把每列做成单个element，这样到时候直接隐右边就完了。以后如果加列直接复制就完了
2. 最简单的修复就是左边没选不让右边选
3. 也可以如果右边选了左边没选，左边直接同时填上右边干员，但2可能更简单效果更好

**Comment by xulai1001** [comment]
暂时把菜单标题改成了“（第一列干员名字）-相同分支的干员”。我再试试直接按照各列来改吧

**Comment by xulai1001** [comment]
解决：增加了左边没选的判断。左边没选择时，不计算后续的dps提升比例就不会报错了。

https://github.com/xulai1001/akdata/commit/5744b85ff5cdcf74ccfcbb58dbd0561380ea3da5#diff-1576e45ee6057168d83e23c1e549b2725896d2127fc0204044bed1222cb5e50eL838
