### ISSUE TITLE
dps表格打不开了

### ISSUE THREAD

**Issue by xuduo** [xulai1001/akdata#2]
![屏幕截图 2021-07-23 110822](https://user-images.githubusercontent.com/1247293/126733394-bcc4cc35-a232-477c-b673-d4919c05e597.png)
![屏幕截图 2021-07-23 110806](https://user-images.githubusercontent.com/1247293/126733404-a5fc55bf-f1ca-43ff-9323-df14a9f3a55e.png)

**Comment by xulai1001** [comment]
已修复。感谢报告
原因是character_ranking没有加载新版本计算器需要的dps_anim.json。
在 [commit e13f0be](https://github.com/xulai1001/akdata/commit/e13f0bee3629bdfa60da51624bad6bc94e933699) 中已经修复。
