### ISSUE TITLE
夏栎的平均DPS/HPS 显示为黑色(物伤)，应为蓝色(法伤)或绿色(治疗)

### ISSUE THREAD

**Issue by Iamanorange** [xulai1001/akdata#22]
![image](https://github.com/xulai1001/akdata/assets/6018925/3b3a98c3-e3a7-4bd2-98a3-7cf911ababba)
突然发现对于既能奶又能打的干员，技能DPS/HPS 和平均DPS/HPS 的着色逻辑好像有点复杂。但是无论如何夏栎的DPS/HPS 都不应该是黑色(物伤)吧？

**Comment by xulai1001** [comment]
印象里混伤的都是黑色吧

**Comment by xulai1001** [comment]
单独选择时是蓝色，但是选的干员多了就会变成黑色……
调查中

**Comment by xulai1001** [comment]
甚至可以搞出三色夏栎……_(:з」∠)_
![image](https://github.com/xulai1001/akdata/assets/2126803/51b54e75-7178-4575-baaf-d6f8c788185f)

**Comment by Iamanorange** [comment]
![image](https://github.com/xulai1001/akdata/assets/6018925/926e990e-47ce-4331-8fb6-6afdd866c4dd)
瑕光3技能有2个问题：
1. 技能DPS显示为黑色，但实际应为法伤+治疗；
2. 平均DPS中没有分离物理DPS和法伤DPS。

**Comment by xulai1001** [comment]
25b02e7 稍微重构了伤害颜色显示的部分。现在可以dps、hps分开显示了
同时增加了表示护盾和掉血（hps<0）的颜色。

平均DPS不区分伤害类型的，需要在伤害表弹出窗口中查看

**Comment by xulai1001** [comment]
计算器的开发群是284807059，也欢迎dalao来群讨论哦

**Comment by xulai1001** [comment]
计算器的开发群是284807059，也欢迎dalao来群讨论哦
