### ISSUE TITLE
最新版Edge浏览器无法弹出窗口选择干员

### ISSUE THREAD

**Issue by dvdvcd** [xulai1001/akdata#4]
最新版Edge浏览器无法弹出窗口选择干员
![Snipaste_2022-06-20_18-12-53](https://user-images.githubusercontent.com/107849742/174580151-e766e806-1b08-4572-a8fb-310a0ced9171.png)
![Snipaste_2022-06-20_18-10-26](https://user-images.githubusercontent.com/107849742/174579694-f3d8067a-f135-445f-9c51-ca1a9a0b7f10.png)

**Comment by dvdvcd** [comment]
不咋用的老版本QQ浏览器竟然没有这问题，意外之喜
浏览器: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3861.400 QQBrowser/10.7.4313.400

![Snipaste_2022-06-23_23-42-43](https://user-images.githubusercontent.com/107849742/175342262-290c2254-fcc3-4cc5-9037-fd342cdd39bd.png)
![Snipaste_2022-06-23_23-43-12](https://user-images.githubusercontent.com/107849742/175342272-341340be-9fdd-4c13-9b41-9617947652bb.png)

**Comment by xulai1001** [comment]
[0acc8eb](https://github.com/xulai1001/akdata/commit/0acc8eb6f8d8c8734b95fac29121546c54b8870a)
尝试修复

**Comment by Granine** [comment]
Bug 重现，推测为相同问题 @xulai1001
